// <auto-generated />
using System;
using EksiSozluk;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EksiSozluk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220105135757_Db_Akademi")]
    partial class Db_Akademi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EksiSozluk.Categories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Kategori Adı");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EksiSozluk.Konu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Catg_ID")
                        .HasColumnType("int");

                    b.Property<bool>("CountWrite")
                        .HasColumnType("bit")
                        .HasColumnName("KonuYaziSayisi");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("TarihSaat");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Açıklama");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Konu Başlığı");

                    b.HasKey("ID");

                    b.HasIndex("Catg_ID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("EksiSozluk.Kullanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KonuID")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("KullaniciAdi");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("KonuKullanici", b =>
                {
                    b.Property<int>("KonularID")
                        .HasColumnType("int");

                    b.Property<int>("KullanicilarID")
                        .HasColumnType("int");

                    b.HasKey("KonularID", "KullanicilarID");

                    b.HasIndex("KullanicilarID");

                    b.ToTable("KonuKullanici");
                });

            modelBuilder.Entity("EksiSozluk.Konu", b =>
                {
                    b.HasOne("EksiSozluk.Categories", "Category")
                        .WithMany("Konular")
                        .HasForeignKey("Catg_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KonuKullanici", b =>
                {
                    b.HasOne("EksiSozluk.Konu", null)
                        .WithMany()
                        .HasForeignKey("KonularID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EksiSozluk.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullanicilarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EksiSozluk.Categories", b =>
                {
                    b.Navigation("Konular");
                });
#pragma warning restore 612, 618
        }
    }
}
